# Site settings
title: Austin Adams
description: Portfolio Website Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "AustinJAdams.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Austin Adams
user_description: I am currently working in my role as a Research Assistant at the Federal Reserve Board of Governors in the Global Capital Markets Section. This section deals mainly with international financial markets. More specifically, my focus inside the section is on international fixed-income markets. In the section, I work as the point contact for foreign fixed-income markets for other sections. I also create and maintain fixed-income data used by the entire Board.<br> I have extensive coding experience both from my role and outside projects. Some of these projects include individual research projects and writing personal trading systems where I leverage programing languages such as Python, R, and C++. My role ends in July 2022, so I am currently looking for opportunities in finance research. Please feel free to reach out using the email icon above the "About Me" button.

user_title: Global Capital Markets Research Assistant at the Federal Reserve Board
email: me@ajadams.co
# twitter_username: lorem_ipsum
github_username:  AustinJAdams
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-143245770-1"

exclude: ['package.json', 'src' , 'node_modules']
